### ISSUE TITLE
build faild for pixel4a

### ISSUE THREAD

**Issue by tnakamur** [TeamWin/android_bootable_recovery#69]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [ ] I have read the FAQ (https://twrp.me/FAQ/)
- [○] I have searched for my issue and it does not already exist

**Device codename**: pixel4a sunfish

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
i'm trying build TWRP for pixel4a(sunfish) using minimal omni10 manifest.
The build failed and the error message is below.

In file included from bootable/recovery/gui/text.cpp:45:
In file included from bootable/recovery/gui/objects.hpp:36:
In file included from bootable/recovery/gui/../partitions.hpp:30:
bootable/recovery/gui/../twrpApex.hpp:18:10: fatal error: 'zip_archive/zip_archive.h' file not found
#include <zip_archive/zip_archive.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Does anyone build completely success android-10 source?
How do I fix this error?

My manifest file is here.
https://github.com/tnakamur/platform_manifest_twrp_omni/tree/twrp-10.0

My device tree is here.
https://github.com/tnakamur/android_device_google_sunfish/tree/android-10.0

My kernel tree is here.
https://github.com/tnakamur/android_device_google_sunfish-kernel
https://github.com/tnakamur/android_kernel_google_sunfish

The build log is here.
https://gist.github.com/tnakamur/3858e17c101bbd59cb85f0bec90b111c

**Comment by tnakamur** [comment]
I use new minimal manifest, past this error.
But, next error appears.

I search same error, I find this.
https://www.mail-archive.com/android-building@googlegroups.com/msg02214.html

I use Ubuntu 18.04, I install fontconfig ttf-droid freetype.
But same error appears.

This is error message.

build /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/installing_text.png
FAILED: /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/installing_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/installing_security_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/erasing_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/error_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/no_command_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/cancel_wipe_data_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/factory_data_reset_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/try_again_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/wipe_data_confirmation_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/wipe_data_menu_header_text.png
/bin/bash -c "(rm -rf /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates ) && (mkdir -p /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates ) && (true ) && (rm -rf /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/ ) && (mkdir -p /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates/ ) && (java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_installing --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//installing_text.png --center_alignment && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//installing_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//installing_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_installing_security --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//installing_security_text.png --center_alignment && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//installing_security_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//installing_security_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_erasing --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//erasing_text.png --center_alignment && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//erasing_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//erasing_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_error --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//error_text.png --center_alignment && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//error_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//error_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_no_command --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//no_command_text.png --center_alignment && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//no_command_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//no_command_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_cancel_wipe_data --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//cancel_wipe_data_text.png  && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//cancel_wipe_data_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//cancel_wipe_data_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_factory_data_reset --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//factory_data_reset_text.png  && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//factory_data_reset_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//factory_data_reset_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_try_again --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//try_again_text.png  && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//try_again_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//try_again_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_wipe_data_menu_header --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//wipe_data_menu_header_text.png  && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//wipe_data_menu_header_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//wipe_data_menu_header_text.png > /dev/null &&    java -jar /home/takahiro/twrp/out/host/linux-x86/framework/RecoveryImageGenerator.jar --image_width \$((1080 - 10)) --text_name recovery_wipe_data_confirmation --font_dir /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_font_files_intermediates --resource_dir bootable/recovery/tools/recovery_l10n/res/ --output_file /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//wipe_data_confirmation_text.png  && /home/takahiro/twrp/out/host/linux-x86/bin/zopflipng -y --iterations=1 --filters=0 /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//wipe_data_confirmation_text.png /home/takahiro/twrp/out/target/product/sunfish/obj/PACKAGING/recovery_text_res_intermediates//wipe_data_confirmation_text.png > /dev/null && true )"
Picked up _JAVA_OPTIONS: -Xmx4g
Exception in thread "main" java.io.IOException: Can not find the font file Roboto-Regular for language en
        at com.android.recovery.tools.ImageGenerator.loadFontsByLocale(ImageGenerator.java:399)
        at com.android.recovery.tools.ImageGenerator.createGraphics(ImageGenerator.java:492)
        at com.android.recovery.tools.ImageGenerator.generateImage(ImageGenerator.java:605)
        at com.android.recovery.tools.ImageGenerator.main(ImageGenerator.java:755)

The build log is here
https://gist.github.com/tnakamur/3858e17c101bbd59cb85f0bec90b111c

**Comment by tnakamur** [comment]
At last I built TWRP for sunfish success.
I used minimal twrp manifest, but it was build error.
I used not-minimal twrp manifest, so it was build success.
